/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Posts {
  body: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  featured: Generated<boolean>;
  id: Generated<string>;
  meta: Generated<Json | null>;
  published_at: Timestamp | null;
  rendered_body: string | null;
  slug: string;
  status: Generated<string>;
  summary: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  posts: Posts;
}
