export const GAMES = [
  {
    id: "1",
    name: "Alias",
    description:
      "Объясняй слова без их названия! Сможешь ли ты перехитрить друзей?",
    icon: "🎭",
    url: "/alias",
    bgColor: "from-blue-400 to-indigo-500",
    borderColor: "border-blue-400",
    hoverColor: "hover:shadow-blue-200",
  },
  {
    id: "2",
    name: "Фанты",
    description:
      "Весёлые задания для компании! Испытай себя в забавных испытаниях!",
    icon: "🎲",
    url: "/fanti",
    bgColor: "from-amber-400 to-orange-500",
    borderColor: "border-amber-400",
    hoverColor: "hover:shadow-amber-200",
  },
  {
    id: "3",
    name: "Ассоциации",
    description: "Соединяй слова, ищи неожиданные связи и удивляй друзей!",
    icon: "💡",
    url: "/associations",
    bgColor: "from-blue-400 to-cyan-500",
    borderColor: "border-blue-400",
    hoverColor: "hover:shadow-blue-200",
  },
  {
    id: "4",
    name: "Шпион",
    description: "Кто среди вас шпион? Определи его, пока не стало поздно!",
    icon: "🕶️",
    url: "/spy",
    bgColor: "from-gray-600 to-gray-800",
    borderColor: "border-gray-600",
    hoverColor: "hover:shadow-gray-300",
  },
  {
    id: "5",
    name: "Крокодил",
    description: "Показывай слова без слов! Угадай быстрее всех!",
    icon: "🐊",
    url: "/crocodile",
    bgColor: "from-green-400 to-emerald-500",
    borderColor: "border-green-400",
    hoverColor: "hover:shadow-green-200",
  },
  {
    id: "6",
    name: "Слова на скорость",
    description: "Назови как можно больше слов по теме и букве за время!",
    icon: "⚡",
    url: "/words-rush",
    bgColor: "from-yellow-400 to-amber-500",
    borderColor: "border-yellow-400",
    hoverColor: "hover:shadow-yellow-200",
  },
  {
    id: "7",
    name: "Круг слов",
    description: "Говори слова с выделенной буквой до истечения времени!",
    icon: "⏳",
    url: "/circle-words",
    bgColor: "from-rose-400 to-pink-500",
    borderColor: "border-rose-400",
    hoverColor: "hover:shadow-pink-200",
  },
  {
    id: "8",
    name: "Бутылочка",
    description: "На кого покажет бутылочка?",
    icon: "🍾",
    url: "/bottle",
    bgColor: "from-pink-400 to-fuchsia-500",
  },
];
